"""Disables one check at a time in a copy of the package and runs the tests against it: python tests/mutate.py

Each mutation below breaks a check the build, the card or verify relies on. The suite must fail (pytest exit 1) for every one; a test run that errors instead does not count as caught. Exits 0 when all are caught, 1 otherwise. The real source is never edited.
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
IGNORE = shutil.ignore_patterns("__pycache__")
# (module, what the mutation breaks, code to replace, replacement). Each code string must occur exactly once in its module.
MUTATIONS = [
    ("nfip.py", "freshness: overdue readings never alert", "elif age >= MAX_UNVERIFIED_HOURS:", "elif False:"),
    ("nfip.py", "freshness: exact age limit is allowed", "elif age >= MAX_UNVERIFIED_HOURS:", "elif age > MAX_UNVERIFIED_HOURS:"),
    ("nfip.py", "freshness: newer reading hides stale peer", "age = max(ages) if len(ages) == len(readings) else None", "age = min(ages) if len(ages) == len(readings) else None"),
    ("nfip.py", "freshness: source drift ignored", 'status = "changed" if changed else "current"', 'changed = False\n        status = "current"'),
    ("census.py", "compare: never reports", "if counts.get((state, kind), 0) != expected]", "if False]"),
    ("census.py", "parse_units: duplicates allowed", "    if duplicates:\n        raise SourceChanged(f\"duplicate census ids", "    if False:\n        raise SourceChanged(f\"duplicate census ids"),
    ("census.py", "check_sha256: no pin", "    if actual != expected:\n", "    if False:\n"),
    ("locus.py", "lopsided: any share", "n >= MIN_SHARE * total", "n >= 0"),
    ("locus.py", "alias guard off", "    if unused:\n", "    if False:\n"),
    ("locus.py", "duplicate-match guard off", "    if duplicates:\n        raise SourceChanged(f\"LOCUS jurisdictions matched", "    if False:\n        raise SourceChanged(f\"LOCUS jurisdictions matched"),
    ("locus.py", "choose: text never settles", "        if len(pool) == 1:\n            return pool[0], \"text_type\"", "        if False:\n            return pool[0], \"text_type\""),
    ("store.py", "412 not treated as conflict", "if status == CONFLICT:", "if False:"),
    ("store.py", "landed commit never adopted", "                return head\n", "                return None\n"),
    ("store.py", "superseded store keeps calling", "        if self.superseded:\n            raise self.superseded\n", ""),
    ("store.py", "busy Hub or dropped connection not retried", "except (HfHubHTTPError, *TRANSIENT) as error:", "except HfHubHTTPError as error:"),
    ("store.py", "card the Hub rejects retried", "TRANSIENT = (httpx.TransportError, json.JSONDecodeError)", "TRANSIENT = (httpx.TransportError, ValueError)"),
    ("store.py", "failure without a status raised at once", "or (http and status not in RETRYABLE):", "or status not in RETRYABLE:"),
    ("verify.py", "crosswalk id not checked against governments", "row[\"census_id\"] not in government_ids", "False"),
    ("verify.py", "crosswalk judged against a rejected table", "check_crosswalk(crosswalk, None if governments is None else {", "check_crosswalk(crosswalk, set() if governments is None else {"),
    ("verify.py", "card not compared", "if store.read_text(CARD) != card:", "if False:"),
    ("verify.py", "ORG02 mismatches dropped", "problems += [f\"CG2200ORG02: {mismatch}\" for mismatch in mismatches]", "pass"),
    ("verify.py", "pins not compared", "!= pin:", "!= pin and False:"),
    ("verify.py", "stats not compared", "            if stats != manifest.get(\"stats\"):", "            if False:"),
    ("verify.py", "sha not compared", "sha256s.get(path) != entry.get(\"sha256\")", "False"),
    ("http.py", "challenge retried as a 403", "response.status_code == 403 and (", "False and ("),
    ("http.py", "no pacing", "        if at > now:\n", "        if False:\n"),
    ("cli.py", "dirty tree may publish", "code[\"dirty\"] is not False", "False"),
    ("build.py", "unchanged ignores the card", " and store.read_text(CARD) == render(manifest)", ""),
    ("build.py", "LOCUS row count not compared", "    if read != stated:\n", "    if False:\n"),
    ("card.py", "review claimed for unread names", "    if differs and not unread:", "    if differs:"),
    ("nylaws.py", "NY part: count change while paging ignored", "if page[\"total_count\"] != expected:", "if False:"),
    ("nylaws.py", "NY part: repeated pages accepted", "    if len(items) != expected:\n", "    if False:\n"),
    ("nylaws.py", "NY part: no window limit", "    if expected > WINDOW:\n", "    if False:\n"),
    ("nylaws.py", "NY: month too large read anyway", "raise SourceChanged(f\"{error}: the harvest needs a finer split\") from None", "continue"),
    ("nylaws.py", "NY: category that moved accepted", "    if not after == before == sum(years.values()) == len(items):\n", "    if False:\n"),
    ("nylaws.py", "NY: changed year not read again", "REPASSES = 1", "REPASSES = 0"),
    ("nylaws.py", "NY rows: undocumented fields accepted", "        if set(fields) != set(FIELDS):\n", "        if False:\n"),
    ("nylaws.py", "NY rows: deleted or unreleased accepted", "if item[\"current_version\"] is not True or item[\"deleted_date\"] is not None or item[\"released_and_not_expired\"] is not True:", "if False:"),
    ("nylaws.py", "NY rows: signed link accepted", "if not item[\"share\"] or not SHARE.fullmatch(item[\"share\"]):", "if False:"),
    ("nylaws.py", "NY rows: several values accepted", "    if len(values) > 1:\n", "    if False:\n"),
    ("nylaws.py", "NY rows: undated accepted", "        if value[\"dateFiled\"] is None:\n", "        if False:\n"),
    ("nylaws.py", "NY rows: odd year accepted", "if year is not None and not (year.isdigit() and len(year) == 4):", "if False:"),
    ("nylaws.py", "NY rows: any time of day accepted", "    if not value.endswith(MIDNIGHTS):\n", "    if False:\n"),
    ("nylaws.py", "NY reading: X CO not a county", "r\"\\s*county$|\\s+co\\.?$\"", "r\"\\s*county$\""),
    ("nylaws.py", "NY reading: repeated title kept", "    if title and words[:len(title)] == title and len(words) > len(title):\n", "    if False:\n"),
    ("nylaws.py", "NY reading: THE kept after the title", "        if words[0] == \"THE\" and len(words) > 1:\n", "        if False:\n"),
    ("nylaws.py", "NY reading: trailing type word kept", "    if municipality_type and len(words) > 1 and words[-1] == municipality_type.upper():\n", "    if False:\n"),
    ("nylaws.py", "NY match: county ignored", "    if county:\n        pool = [entry for entry in pool if entry[\"county\"] == county]\n", ""),
    ("nylaws.py", "NY match: Village read as Town", "\"Village\": \"VILLAGE OF\"", "\"Village\": \"TOWN OF\""),
    ("nylaws.py", "NY index: title and type may disagree", "        if GOVERNMENT_TYPES.get(title) != row[\"government_type\"]:\n", "        if False:\n"),
    ("nylaws.py", "NY posting: UTC days", "    return row[\"posted_at\"].astimezone(NEW_YORK).date()", "    return row[\"posted_at\"].date()"),
    ("nylaws.py", "NY posting: window edge included", "row[\"posted_at\"] > latest - datetime.timedelta(days=RECENT_DAYS)", "row[\"posted_at\"] >= latest - datetime.timedelta(days=RECENT_DAYS)"),
    ("nylaws.py", "NY posting: p90 below nine in ten", "days[-(-9 * len(days) // 10) - 1]", "days[int(0.9 * (len(days) - 1))]"),
    ("nylaws.py", "NY posting: upper median", "waits[(len(waits) - 1) // 2]", "waits[len(waits) // 2]"),
    ("nylaws.py", "NY: misdated filings not listed", "for row in table if row[\"date_filed\"] > posted_on(row)),", "for row in table if False),"),
    ("nylaws.py", "NY: governments without filings not listed", "if census_id not in filed),", "if False),"),
    ("build.py", "NY snapshot not checked against its counts", "    if len(ny) != snapshot[\"total\"] or Counter(str(row[\"date_filed\"].year) for row in ny) != Counter(snapshot[\"years\"]):\n", "    if False:\n"),
    ("verify.py", "NY rows without asset_id pass", "    if None in ids or \"\" in ids:\n", "    if False:\n"),
    ("verify.py", "NY duplicate asset_id pass", "duplicates = [uid for uid, n in ids.items() if uid and n > 1]", "duplicates = []"),
    ("verify.py", "NY manifest year sum not checked", "    if sum(counted.values()) != source.get(\"total\"):\n", "    if False:\n"),
    ("verify.py", "NY row count not checked", "    if len(rows) != source.get(\"total\"):\n", "    if False:\n"),
    ("verify.py", "NY filings by year not checked", "    if differing:\n        problems.append(f\"ny_local_laws: filings by year", "    if False:\n        problems.append(f\"ny_local_laws: filings by year"),
    ("verify.py", "NY signed links pass", "if not row[\"share_url\"] or not nylaws.SHARE.fullmatch(row[\"share_url\"])]", "if False]"),
    ("verify.py", "NY unknown match values pass", "unknown = sorted({row[\"match\"] for row in rows} - set(nylaws.MATCHES))", "unknown = []"),
    ("verify.py", "NY census_id, match, candidates may disagree", "        if (row[\"census_id\"] is None) != unmatched or bool(row[\"candidates\"]) != (row[\"match\"] == \"ambiguous\"):\n", "        if False:\n"),
    ("verify.py", "NY stray census_id passes", "                stray.append(row[key])", "                pass"),
    ("verify.py", "NY mistitled census_id passes", "                mistitled.append(row[key])", "                pass"),
    ("verify.py", "NY judged against a rejected table", "titles = None if governments is None else {", "titles = {} if governments is None else {"),
    ("card.py", "NY unmatched not listed", "        f\"Unmatched, with the number of filings: {listed(ny['unmatched'])}.\",", "        \"Unmatched, with the number of filings: none.\","),
    ("card.py", "NY ambiguous not listed", "        f\"Ambiguous, with the number of filings: {listed(ny['ambiguous'])}.\",", "        \"Ambiguous, with the number of filings: none.\","),
    ("card.py", "NY per-type rates dropped", "    for kind, entry in kinds.items():\n", "    for kind, entry in []:\n"),
    ("card.py", "NY misdated filings not stated", "{misdated(ny['filed_after_posted'])}", ""),
    ("card.py", "NY governments without filings not stated", "    lines += [\"\", without_filings(ny[\"without_filings\"])]\n", ""),
    ("card.py", "NY outside-category gap dropped", "        f\"- {NY_OUTSIDE}\",\n", ""),
    ("cli.py", "run ignores --ny-snapshot", "snapshot = nylaws.load(args.ny_snapshot) if args.ny_snapshot else None", "snapshot = None"),
    ("cli.py", "harvest-ny does not stop cleanly", "        snapshot = nylaws.harvest(fetcher)\n    except (SourceChanged, Blocked, Unavailable) as error:", "        snapshot = nylaws.harvest(fetcher)\n    except () as error:"),
    ("precision.py", "NY check: name in metadata taken as confirmed", "    if in_text(name):\n        return \"confirmed\"", "    if name[0]:\n        return \"confirmed\""),
    ("precision.py", "NY check: other-type names ignored", "    if any(found for _, _, found in other):\n        return \"contradicted\"", "    if False:\n        return \"contradicted\""),
    ("precision.py", "NY check: GENERIC's metadata control ignored", "return \"not_named\" if in_text(generic) else \"no_text\"", "return \"not_named\" if generic[0] else \"no_text\""),
    ("precision.py", "NY check: text counted from metadata hits", "entry[\"with_text\"] += in_text(generic) or in_text(name) or (county is not None and in_text(county))", "entry[\"with_text\"] += bool(generic[0] or name[0])"),
    ("card.py", "NY check paragraph dropped", "        checked(),\n        \"\",\n", ""),
    ("card.py", "NY check: confirmed count typed in", "f\"{found['confirmed']:,} of the {n} were confirmed", "f\"35 of the {n} were confirmed"),
    ("card.py", "NY check: contradictions not stated", "verdict = \"No filing was\" if not contradicted else", "verdict = \"No filing was\" if True else"),
    ("card.py", "NY check: second draw's other names not stated", "    if second[\"other_found\"]:\n", "    if False:\n"),
    ("card.py", "NY check: every filing said to have text", "    if with_text == filings:\n        lines.append(f\"Every filing checked", "    if True:\n        lines.append(f\"Every filing checked"),
    ("card.py", "NY text gap: every filing said to have text", "{'every one' if with_text == filings else f'{with_text:,}'}", "every one"),
    ("precision.py", "NY check: a real county counted as unnamed", " if phrase not in REAL)", ")"),
    ("nyindex.py", "index: export not checked against the State", "    if exported != held:\n", "    if False:\n"),
    ("nyindex.py", "index: State count not compared", "    if len(state) != len(table):\n", "    if False:\n"),
    ("nyindex.py", "index: State header not checked", "if length != RECORD_BYTES or len(data) < 32 + count * length:", "if False:"),
    ("nyindex.py", "index: short State file read", "    if len(data) < 32:\n", "    if False:\n"),
    ("nyindex.py", "index: export header not checked", "    if tuple(lines[0].split(\"\\t\")) != HEADER:\n", "    if False:\n"),
    ("nyindex.py", "index: field count not checked", "        if len(values) != len(HEADER):\n", "        if False:\n"),
    ("nyindex.py", "index: odd year or pages accepted", "        if not (year.isdigit() and len(year) == 4) or not pages.isdigit():\n", "        if False:\n"),
    ("nyindex.py", "index: year 0000 kept as 0", "\"law_year\": int(year) or None,", "\"law_year\": int(year),"),
    ("nyindex.py", "index: type read as written", "    return value.capitalize() if value else value\n", "    return value\n"),
    ("nyindex.py", "index: diaeresis not read as a", ".replace(\"\u00a8\", \"a\")", ""),
    ("nyindex.py", "index: runs of spaces kept", "\" \".join(raw.decode(\"cp1252\").replace(\"\u00a8\", \"a\").split())", "raw.decode(\"cp1252\").replace(\"\u00a8\", \"a\").strip()"),
    ("nyindex.py", "index: search overlap reads the type as written", "nylaws.filing(read_type(row[\"municipality_type\"])", "nylaws.filing((row[\"municipality_type\"])"),
    ("nylaws.py", "NY match: read_type ignored", "row[\"municipality_type\"] if read_type is None else read_type(row[\"municipality_type\"])", "row[\"municipality_type\"]"),
    ("nylaws.py", "NY repeats not counted", "        repeats[date.year] += n - 1\n", "        pass\n"),
    ("nylaws.py", "NY repeats: names compared as written", "return kind, \" \".join((name or \"\").upper().split()), number, filed", "return kind, name, number, filed"),
    ("nylaws.py", "NY repeats: rows without a number counted", " for row in table if row[\"law_number\"] is not None).items():", ").items():"),
    ("verify.py", "index: index_row not checked", "    if sorted(positions) != list(range(1, len(rows) + 1)):\n", "    if False:\n"),
    ("verify.py", "index: rows not compared with the source", "    for field in (\"rows\", \"state_records\"):\n        if len(rows) != source.get(field):\n", "    for field in (\"rows\", \"state_records\"):\n        if False:\n"),
    ("verify.py", "index: rows not compared with the export", "    if changed:\n        problems.append(f\"ny_local_law_index: rows that", "    if False:\n        problems.append(f\"ny_local_law_index: rows that"),
    ("verify.py", "index: missing export lines pass", "    if missing:\n        problems.append(f\"ny_local_law_index: export lines", "    if False:\n        problems.append(f\"ny_local_law_index: export lines"),
    ("verify.py", "index: State records not compared", "    if published != held:\n", "    if False:\n"),
    ("verify.py", "index: type read as written", "check_matches(\"ny_local_law_index\", rows, \"index_row\", governments, problems, nyindex.read_type)", "check_matches(\"ny_local_law_index\", rows, \"index_row\", governments, problems)"),
    ("verify.py", "NY matches not recomputed", "    if rematched:\n", "    if False:\n"),
    ("card.py", "index: unmatched not listed", "        f\"Unmatched, with the number of rows: {listed(index['unmatched'])}.\",", "        \"Unmatched, with the number of rows: none.\","),
    ("card.py", "index: misdated rows not stated", "{index_misdated(index)}", ""),
    ("card.py", "NY repeats gap dropped", "        *repeats_gap(stats[\"ny\"]),\n", ""),
    ("card.py", "NY repeats: always most", "\"all\" if held == total else \"most\" if 2 * held > total else \"the largest shares\"", "\"most\""),
    ("card.py", "NY check: form titles sentence dropped", "    lines.append(form_titles(parts))\n", ""),
    ("card.py", "NY check: unnamed count typed in", "was found in {found:,} of the {asked:,} filings checked, likely", "was found in 7 of the {asked:,} filings checked, likely"),
    ("card.py", "NY check: no-hit form titles branch never taken", "    if not found:\n        return f\"The matched name", "    if False:\n        return f\"The matched name"),
    ("tribes.py", "tribes: not-XML guard off", "raise SourceChanged(f\"the notice is not XML: {error}\") from None", "raise"),
    ("tribes.py", "tribes: stated-count guard off", "    if not found:\n        raise SourceChanged(\"the notice's summary", "    if False:\n        raise SourceChanged(\"the notice's summary"),
    ("tribes.py", "tribes: list headings unchecked", "    if headings != list(LISTS):\n", "    if False:\n"),
    ("tribes.py", "tribes: blank entries allowed", "    if blank:\n", "    if False:\n"),
    ("tribes.py", "tribes: whitespace kept", "return \" \".join(\"\".join(element.itertext()).split())", "return \"\".join(element.itertext()).strip()"),
    ("tribes.py", "tribes: updated notice unchecked", "    if notice[\"updates\"] != PREVIOUS[\"citation\"]:\n", "    if False:\n"),
    ("tribes.py", "tribes: notice SHA-256 unchecked", "    check_sha256(data, notice[\"sha256\"], notice[\"url\"])\n", ""),
    ("tribes.py", "tribes: rules reversed", "        for rule in RULES:\n", "        for rule in reversed(RULES):\n"),
    ("tribes.py", "tribes: rules merged", "            found = [value for value in pool if rule(entry, value)]\n", "            found = [value for value in pool if any(each(entry, value) for each in RULES)]\n"),
    ("tribes.py", "tribes: former name cut at first parenthesis", "            if depth == 0:\n", "            if entry[position] == \")\":\n"),
    ("tribes.py", "tribes: spaced parenthesis not closed up", "    entry = re.sub(r\"\\(\\s+\", \"(\", entry)\n", ""),
    ("tribes.py", "tribes: earlier entries of both lists", "        pool = [value for kind, value in earlier if kind == listed]\n", "        pool = [value for kind, value in earlier]\n"),
    ("tribes.py", "tribes: ambiguous continuation allowed", "            if len(found) > 1:\n", "            if False:\n"),
    ("tribes.py", "tribes: dropped or doubled unchecked", "    if dropped or doubled:\n", "    if False:\n"),
    ("tribes.py", "tribes: doubled not counted", "    doubled = [value for (_, value), n in used.items() if n > 1]\n", "    doubled = []\n"),
    ("tribes.py", "tribes: added count unchecked", "    if len(added) != stated - earlier_stated:\n", "    if False:\n"),
    ("tribes.py", "tribes: every change a rename", "if key(name(row[\"previous_entry\"])) != key(row[\"name\"])", "if True"),
    ("tribes.py", "tribes: unlisted See targets counted", "            if key(target) in names:\n", "            if True:\n"),
    ("verify.py", "tribes: list_row positions unchecked", "    if set(positions) != set(range(1, len(rows) + 1)):\n", "    if False:\n"),
    ("verify.py", "tribes: unknown list values allowed", "    if unknown:\n        problems.append(f\"{name}: list values", "    if False:\n        problems.append(f\"{name}: list values"),
    ("verify.py", "tribes: list order unchecked", "        if places != sorted(places):\n", "        if False:\n"),
    ("verify.py", "tribes: names unchecked", "    misnamed = [row[\"list_row\"] for row in rows if row[\"name\"] != tribes.name(row[\"entry\"] or \"\")]\n", "    misnamed = []\n"),
    ("verify.py", "tribes: doubled continuation allowed", "    if doubled:\n        problems.append(f\"{name}: earlier entries continued", "    if False:\n        problems.append(f\"{name}: earlier entries continued"),
    ("verify.py", "tribes: row counts unchecked", "    for field in (\"rows\", \"entries\"):\n        if len(rows) != source.get(field):\n", "    for field in (\"rows\", \"entries\"):\n        if False:\n"),
    ("verify.py", "tribes: counts need not be integers", "    if not all(isinstance(value, int) for value in counts.values()):\n", "    if False:\n"),
    ("verify.py", "tribes: added count unchecked", "    if added != counts[\"stated\"] - counts[\"previous_stated\"]:\n", "    if False:\n"),
    ("verify.py", "tribes: continuing count unchecked", "    if len(rows) - added != counts[\"previous_entries\"]:\n", "    if False:\n"),
    ("verify.py", "tribes: rows not compared with notice", "    if changed:\n        problems.append(f\"federally_recognized_tribes: rows that", "    if False:\n        problems.append(f\"federally_recognized_tribes: rows that"),
    ("verify.py", "tribes: missing entries unchecked", "    if missing:\n        problems.append(f\"federally_recognized_tribes: entries", "    if False:\n        problems.append(f\"federally_recognized_tribes: entries"),
    ("verify.py", "tribes: counts not compared with notices", "    if differing:\n        problems.append(f\"federally_recognized_tribes: the manifest", "    if False:\n        problems.append(f\"federally_recognized_tribes: the manifest"),
    ("verify.py", "tribes: notice pin unchecked", "(\"federally_recognized_tribes\", \"sha256\"): tribes.NOTICE[\"sha256\"], ", ""),
    ("verify.py", "tribes: rows never checked", "check_tribes(recognized, sources.get(\"federally_recognized_tribes\") or {}, problems)", "None"),
    ("card.py", "tribes: equal-count branch never taken", "    if rows == stated:\n", "    if False:\n"),
    ("card.py", "tribes: fewer and more not told apart", "'fewer' if gap > 0 else 'more'", "'fewer'"),
    ("card.py", "tribes: 'less the referred' always said", "        if rows - len(referred) == stated:\n", "        if True:\n"),
    ("card.py", "tribes: notice quoted for any notice", "says = f\" {tribes.NOTICE_SAYS}\" if source[\"document_number\"] == tribes.NOTICE[\"document_number\"] else \"\"", "says = f\" {tribes.NOTICE_SAYS}\""),
    ("card.py", "tribes: latest check claimed for any notice", "latest = f\", the latest the Federal Register's API found on {day(tribes.LATEST_CHECKED)}\" if source[\"document_number\"] == tribes.NOTICE[\"document_number\"] else \"\"", "latest = f\", the latest the Federal Register's API found on {day(tribes.LATEST_CHECKED)}\""),
    ("card.py", "tribes: gap bullet dropped", "        tribes_gap(manifest[\"sources\"][\"federally_recognized_tribes\"]),\n", ""),
    ("tribes.py", "tribes: respaced entries not counted", "sum(1 for row in same if row[\"entry\"] != row[\"previous_entry\"])", "0"),
    ("tribes.py", "tribes: respaced names not listed", "sorted([row[\"name\"], name(row[\"previous_entry\"])] for row in same if row[\"name\"] != name(row[\"previous_entry\"]))", "[]"),
    ("card.py", "tribes: respaced sentence dropped", "        *respaced(respaced_names),\n", ""),
    ("card.py", "tribes: respaced names not counted", "{f'{len(respaced_names):,}' if respaced_names else 'none'} of those", "none of those"),
    ("nfip.py", "nfip: header unchecked", "    if not records or [cell(value) for value in records[0]] != COLUMNS:\n", "    if not records:\n"),
    ("nfip.py", "nfip: value count unchecked", "        if len(values) != len(COLUMNS):\n", "        if False:\n"),
    ("nfip.py", "nfip: first part's header after the second", "            if not participating:\n                raise SourceChanged(f\"record {record}: the participating", "            if False:\n                raise SourceChanged(f\"record {record}: the participating"),
    ("nfip.py", "nfip: second part's header twice", "            if not participating:\n                raise SourceChanged(f\"record {record}: a second header", "            if False:\n                raise SourceChanged(f\"record {record}: a second header"),
    ("nfip.py", "nfip: other values beside a note allowed", "            if others or bool(name) == bool(county.strip()):\n", "            if bool(name) == bool(county.strip()):\n"),
    ("nfip.py", "nfip: notes not unescaped", "out[-1][\"notes\"].append(\" \".join(html.unescape(name).split()))", "out[-1][\"notes\"].append(\" \".join(name.split()))"),
    ("nfip.py", "nfip: county continuation dropped", "                out[-1][\"county\"] += county\n", "                pass\n"),
    ("nfip.py", "nfip: state prefix unchecked", "        if state is None:\n", "        if False:\n"),
    ("nfip.py", "nfip: duplicate CID allowed", "        if cid in seen:\n", "        if False:\n"),
    ("nfip.py", "nfip: participation column unchecked", "        if values[13] != (\"YES\" if participating else \"NO\"):\n", "        if False:\n"),
    ("nfip.py", "nfip: tribal unchecked", "        if tribal is None:\n", "        if False:\n"),
    ("nfip.py", "nfip: program unchecked", "        if values[12] and values[12] not in PROGRAMS:\n", "        if False:\n"),
    ("nfip.py", "nfip: status note unchecked", "        if status_note is not None and status_note not in STATUS_NOTES[participating]:\n", "        if False:\n"),
    ("nfip.py", "nfip: note allowed on a plain date", "    if note is not None:\n        raise SourceChanged(", "    if False:\n        raise SourceChanged("),
    ("nfip.py", "nfip: impossible date read as none", "        except ValueError:\n            raise SourceChanged(f\"record {record}: {column} is {value!r}, not a date\") from None\n", "        except ValueError:\n            pass\n"),
    ("nfip.py", "nfip: no pivot year", "return 1900 + two if two >= PIVOT else 2000 + two", "return 2000 + two"),
    ("nfip.py", "nfip: number pattern unchecked", "    if not re.fullmatch(pattern, value):\n", "    if False:\n"),
    ("nfip.py", "nfip: missing second part allowed", "    if participating:\n        raise SourceChanged(\"the report has no part", "    if False:\n        raise SourceChanged(\"the report has no part"),
    ("nfip.py", "nfip: name not stripped", "\"community_name\": values[1].strip(),", "\"community_name\": values[1],"),
    ("nfip.py", "nfip: API duplicates allowed", "    if doubled:\n", "    if False:\n"),
    ("nfip.py", "nfip: API identity unchecked", "    if identity:\n", "    if False:\n"),
    ("nfip.py", "nfip: API name not stripped", "\"community_name\": (item[\"communityName\"] or \"\").strip(),", "\"community_name\": item[\"communityName\"] or \"\","),
    ("nfip.py", "nfip: API-only communities miscounted", "if item[\"communityIdNumber\"] not in listed)", "if True)"),
    ("nfip.py", "nfip: later dates not listed", "if row[column] is not None and row[column] > day:", "if False:"),
    ("verify.py", "verify nfip: cid unchecked", "    if malformed:\n        problems.append(f\"{name}: cid null", "    if False:\n        problems.append(f\"{name}: cid null"),
    ("verify.py", "verify nfip: duplicates unchecked", "        if repeated:\n            problems.append(f\"{name}: duplicate {field}", "        if False:\n            problems.append(f\"{name}: duplicate {field}"),
    ("verify.py", "verify nfip: state unchecked", "    if misplaced:\n        problems.append(f\"{name}: state is not", "    if False:\n        problems.append(f\"{name}: state is not"),
    ("verify.py", "verify nfip: entry and sanction unchecked", "    if inconsistent:\n        problems.append(f\"{name}: a date or note", "    if False:\n        problems.append(f\"{name}: a date or note"),
    ("verify.py", "verify nfip: part order unchecked", "    if ordered != sorted(ordered, reverse=True):\n", "    if False:\n"),
    ("verify.py", "verify nfip: counts unchecked", "for field, value in counts.items() if source.get(field) != value}", "for field, value in counts.items() if False}"),
    ("verify.py", "verify nfip: API count unchecked", "    if api.get(\"in_report\") != len(rows):\n", "    if False:\n"),
    ("verify.py", "verify nfip: later dates unchecked", "    if after != source.get(\"after_retrieval\"):\n", "    if False:\n"),
    ("verify.py", "verify nfip: rows not compared", "    if changed:\n        problems.append(f\"nfip_communities: rows", "    if False:\n        problems.append(f\"nfip_communities: rows"),
    ("verify.py", "verify nfip: missing rows not reported", "    if missing:\n        problems.append(f\"nfip_communities: communities in {report}", "    if False:\n        problems.append(f\"nfip_communities: communities in {report}"),
    ("verify.py", "verify nfip: regenerated report compared", "    if hashlib.sha256(data).hexdigest() != source.get(\"sha256\"):\n", "    if False:\n"),
    ("card.py", "card nfip: classes in text order", "key=lambda item: int(item[0])", "key=lambda item: item[0]"),
    ("card.py", "card nfip: distant dates not named", "datetime.date.fromisoformat(value).year > read.year + 5]", "datetime.date.fromisoformat(value).year > read.year + 50]"),
    ("card.py", "card nfip: differences not cut at five", "for cid, ours, theirs in cases[:5])", "for cid, ours, theirs in cases)"),
    ("http.py", "http: FEMA's crawl delay ignored", "max(self.interval, HOST_INTERVALS.get(host, 0.0))", "self.interval"),
    ("cli.py", "cli: harvest-nfip saves without reconciling", "        reconciled = nfip.reconcile(table, snapshot[\"api\"])\n", "        reconciled = {\"rows\": 28, \"only_in_api\": {\"participating\": 1, \"not_participating\": 2}}\n"),
    ("nfip.py", "snapshot: deflated", "            info.compress_type = zipfile.ZIP_STORED\n", "            info.compress_type = zipfile.ZIP_DEFLATED\n"),
    ("nfip.py", "snapshot: dated when written", "            info = zipfile.ZipInfo(name, date_time=ZIP_TIME)\n", "            info = zipfile.ZipInfo(name, date_time=datetime.datetime.now().timetuple()[:6])\n"),
    ("nfip.py", "snapshot: reading times not compared", "    return sorted(key for key in read if read[key] != recorded[key])", "    return sorted(key for key in read if read[key] != recorded[key] and not key.endswith(\"retrieved_at\"))"),
    ("build.py", "snapshot: listed but not committed", "    files[nfip.SNAPSHOT] = local\n", ""),
    ("cli.py", "snapshot: bytes not checked against the manifest", "    if data is None or hashlib.sha256(data).hexdigest() != entry.get(\"sha256\"):\n", "    if data is None:\n"),
    ("cli.py", "snapshot: reading not checked against the manifest", "    if differ:\n        raise SourceChanged(f\"{nfip.SNAPSHOT} is not the reading", "    if False:\n        raise SourceChanged(f\"{nfip.SNAPSHOT} is not the reading"),
    ("cli.py", "snapshot: a refused run never falls back", "        stored = stored_nfip_snapshot(store)\n        if stored is None:\n            raise\n", "        raise\n"),
    ("verify.py", "snapshot: verify skips the stored files", "        if nfip.SNAPSHOT in entries and nfip.SNAPSHOT in listed:\n", "        if False:\n"),
    ("verify.py", "snapshot: verify ignores their reading", "    if differ:\n        problems.append(f\"{nfip.SNAPSHOT} is not the reading", "    if False:\n        problems.append(f\"{nfip.SNAPSHOT} is not the reading"),
    ("verify.py", "snapshot: unreadable stored files crash verify", "    except (zipfile.BadZipFile, KeyError, ValueError, TypeError) as error:\n", "    except ZeroDivisionError as error:\n"),
    ("verify.py", "snapshot: fema.gov refusing crashes verify", "    except (Blocked, Unavailable, httpx.HTTPStatusError) as error:\n        return {\"same_file\": None", "    except ZeroDivisionError as error:\n        return {\"same_file\": None"),
    ("card.py", "snapshot: card does not list the file", "if nfip.SNAPSHOT in entries else [])", "if False else [])"),
    ("card.py", "snapshot: card says a refused run writes nothing", "    if nfip.SNAPSHOT not in manifest[\"files\"]:\n        return (f\"On September 27", "    if True:\n        return (f\"On September 27"),
]


def main():
    stale = [f"{module}: {label}" for module, label, old, _ in MUTATIONS if (REPO / "local_laws" / module).read_text().count(old) != 1]
    if stale:
        raise SystemExit(f"the code behind these mutations has changed or repeats; update them: {stale}")
    missed = []
    with tempfile.TemporaryDirectory(prefix="local-laws-mutate-") as scratch:
        copy = Path(scratch).resolve()
        shutil.copytree(REPO / "tests", copy / "tests", ignore=IGNORE)
        shutil.copytree(REPO / ".github", copy / ".github")
        env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1", PYTHONPATH=str(copy))
        for module, label, old, new in MUTATIONS:
            shutil.rmtree(copy / "local_laws", ignore_errors=True)
            shutil.copytree(REPO / "local_laws", copy / "local_laws", ignore=IGNORE)
            path = copy / "local_laws" / module
            path.write_text(path.read_text().replace(old, new))
            result = subprocess.run([sys.executable, "-m", "pytest", "-p", "no:cacheprovider", "-q", "-x", "--rootdir", str(copy), str(copy / "tests")], capture_output=True, text=True, env=env, cwd=copy)
            failed = next((line for line in result.stdout.splitlines() if line.startswith(("FAILED", "ERROR"))), "")
            print(f"exit {result.returncode}  {module:10} {label:46} {failed[:100]}", flush=True)
            if result.returncode != 1:
                missed.append(label)
    print(f"not caught: {missed}" if missed else f"all {len(MUTATIONS)} mutations were caught")
    return 1 if missed else 0


if __name__ == "__main__":
    raise SystemExit(main())
